const SHOP_DATA = {
  Chairs: {
    id: 1,
    category: "Chairs",
    routeName: "chairs",
    items: [
      {
        id: 1,
        category: "Chairs",
        name: "Reddit Gaming Chair",
        imageUrl: "https://i.ibb.co/SR0jgk4/Artiss-Chair.webp",
        price: 25,
      },

      {
        id: 3,
        category: "Chairs",
        name: "CEO Office Chair",
        imageUrl: "https://i.ibb.co/NFRHM8x/Executive-Chair.webp",
        price: 994,
      },
      {
        id: 4,
        category: "Chairs",
        name: "Ergonomic Office Chair",
        imageUrl: "https://i.ibb.co/GQ7f8bY/Ergonomic-Office-Chair.webp",
        price: 25,
      },
      {
        id: 5,
        name: "Steam Sale Office Chair",
        category: "Chairs",
        imageUrl: "https://i.ibb.co/bBpDRbB/Volnir-Mesh-Ergonomic-Office-Chair.webp",
        price: 279,
      },
      {
        id: 6,
        name: "Vintage Chair",
        category: "Chairs",
        imageUrl: "https://i.ibb.co/ZTkxVh1/Vintage-Chair.webp",
        price: 789,
      },
      {
        id: 7,
        name: "Homer",
        category: "Chairs",
        imageUrl: "https://i.ibb.co/2Pspvqc/homer.jpg",
        price: 25,
      },
      {
        id: 8,
        name: "Hermes",
        category: "Chairs",
        imageUrl: "https://i.ibb.co/bFgbn6p/Hermes.jpg",
        price: 25,
      },
      {
        id: 9,
        name: "Chair that spins",
        category: "Chairs",
        imageUrl: "https://i.ibb.co/b2GYKWW/Eclipse-Chair.webp",
        price: 25,
      },
      {
        id: 10,
        name: "Classic Hickory Office Chair",
        category: "Chairs",
        imageUrl: "https://i.ibb.co/1ZNj29N/Classic-Hickory-Office-Chair.webp",
        price: 25,
      },
      {
        id: 11,
        name: "Comfort Office Chair",
        category: "Chairs",
        imageUrl: "https://i.ibb.co/B3pDKkD/Comfort-Office-Chair.webp",
        price: 25,
      },
      {
        id: 12,
        name: "Leander",
        category: "Chairs",
        imageUrl: "https://i.ibb.co/qCQSsWj/Leander.jpg",
        price: 25,
      },
      {
        id: 13,
        category: "Chairs",
        name: "Boring Office Chair",
        imageUrl: "https://i.ibb.co/2twkD2F/Monochrome-chair.webp",
        price: 25,
      },
      {
        id: 14,
        category: "Chairs",
        name: "Baerus",
        imageUrl: "https://i.ibb.co/sR13b0N/baerus.jpg",
        price: 25,
      },
      {
        id: 15,
        name: "Athena",
        category: "Chairs",
        imageUrl: "https://i.ibb.co/V2wMJvZ/athena.jpg",
        price: 25,
      },
    ],
  },

  Lights: {
    id: 2,
    category: "Lights",
    routeName: "lights",
    items: [
      {
        id: 16,
        name: "Svallet Work Lamp",
        category: "Lights",
        imageUrl: "https://i.ibb.co/bzsXybM/svallet-work-lamp-dark-grey-white.webp",
        price: 999,
      },
      {
        id: 17,
        name: "Nymane Work Lamp",
        category: "Lights",
        imageUrl: "https://i.ibb.co/SV056gT/nymane-work-wall-lamp-anthracite.webp",
        price: 999,
      },
      {
        id: 18,
        name: "Spannland Led Work Lamp",
        category: "Lights",
        imageUrl: "https://i.ibb.co/GF1d7bK/spannland-led-work-lamp-with-storage-dimmable.webp",
        price: 999,
      },
      {
        id: 19,
        name: "Ankarspel Work Lamp",
        category: "Lights",
        imageUrl: "https://i.ibb.co/7vFsh7h/ankarspel-work-lamp-pewter-effect-1067917-pe852820-s5.webp",
        price: 199,
      },
      {
        id: 20,
        name: "Forsa",
        category: "Lights",
        imageUrl: "https://i.ibb.co/b5tbgCs/Forsa.webp",
        price: 999,
      },
    ],
  },

  Sofas: {
    id: 3,
    category: "Sofas",
    routeName: "sofas",
    items: [
      {
        id: 21,
        name: " Helmer Desk and Chair ",
        category: "Sofas",
        imageUrl: " https://i.ibb.co/3pVmYH6/utespelare-helmer-desk-chair-and-drawer-unit-black-1004842-pe825226-s5.webp",
        price: 19,
      },
      {
        id: 22,
        name: "Alexa Desk ",
        category: "Sofas",
        imageUrl: "https://i.ibb.co/KVGZVFj/alex-desk-white-0977658-pe813725-s5.webp",
        price: 9999,
      },
      {
        id: 23,
        name: "Fredde Gaming Desk",
        category: "Sofas",
        imageUrl: "https://i.ibb.co/5cg6wwR/Fredde-gaming-desk-black-0736008-pe740351-s5.webp ",
        price: 9999,
      },
      {
        id: 24,
        name: "Hemnes with add on unit",
        category: "Sofas",
        imageUrl: "https://i.ibb.co/R9Y5ypy/hemnes-desk-with-add-on-unit-white-stain-light-brown-1176762-pe895141-s5.webp",
        price: 999,
      },
      {
        id: 25,
        name: "Lommarp Desk",
        category: "Sofas",
        imageUrl: "https://i.ibb.co/GvnS1B4/lommarp-desk-dark-blue-green-0770954-pe755650-s5.webp",
        price: 999,
      },
      {
        id: 26,
        name: "Malm Desk",
        category: "Sofas",
        imageUrl: "https://i.ibb.co/7kY8kBV/malm-desk-with-pull-out-panel-white-0735980-pe740314-s5.webp",
        price: 999,
      },
      {
        id: 27,
        name: "Micke with add on unit",
        category: "Sofas",
        imageUrl: "https://i.ibb.co/BKC67Jy/micke-add-on-unit-high-white-1162647-pe889914-s5.webp",
        price: 999,
      },
      {
        id: 28,
        name: "Micke Corner Workstation",
        category: "Sofas",
        imageUrl: "https://i.ibb.co/tJM55hz/micke-corner-workstation-black-brown-0734327-pe739443-s5.webp",
        price: 999,
      },
      {
        id: 29,
        name: "Torald desk and chair",
        category: "Sofas",
        imageUrl: "https://i.ibb.co/7YD0MqY/uppspel-gaming-desk-black-1039805-pe840452-s5.webp ",
        price: 999,
      },
      {
        id: 30,
        name: "Utspelare Gaming desk",
        category: "Sofas",
        imageUrl: "https://i.ibb.co/CHLDgwS/utespelare-gaming-desk-black-0985179-pe816538-s5.webp ",
        price: 199,
      },
      {
        id: 31,
        name: "Bekant chair and desk",
        category: "Sofas",
        imageUrl: "https://i.ibb.co/xX2HBhj/bekant-desk-white-black.webp ",
        price: 999,
      },
      {
        id: 32,
        name: "Work desk - Defintely not a Sofa",
        category: "Sofas",
        imageUrl: "https://i.ibb.co/6yGrmpV/tempestes.jpg ",
        price: 9999,
      },
    ],

  },

  Stools: {
    id: 4,
    category: "Technology",
    routeName: "stools",
    items: [
      {
        id: 33,
        name: "Macbook Air 13-3",
        category: "Stools",
        imageUrl: "https://i.ibb.co/sQVDYCG/Mac-book-air-13-3.webp ",
        price: 999,
      },
      {
        id: 34,
        name: "Microsoft Surface laptop 5",
        category: "Stools",
        imageUrl: " https://i.ibb.co/h8vRCk7/Microsoft-Surface-laptop-5.webp ",
        price: 999,
      },

      {
        id: 35,
        name: "Envy 2-in-1",
        category: "Stools",
        imageUrl: "https://i.ibb.co/9sJf4fk/HP-Envy-2-in-1.webp  ",
        price: 999,
      },
      {
        id: 36,
        name: "Ultra-wide Monitor",
        category: "Stools",
        imageUrl: "https://i.ibb.co/ykwkh3F/Ultra-wide-Monitor.webp ",
        price: 999,
      },
      {
        id: 37,
        name: "Logi-Tech pro-HD Webcam",
        category: "Stools",
        imageUrl: "https://i.ibb.co/f16w3SN/Logi-Tech-pro-HD-Webcam.webp ",
        price: 999,
      },
      {
        id: 38,
        name: "Wireless Keyboard and Mouse",
        category: "Stools",
        imageUrl: " https://i.ibb.co/WcNY7yz/Wireless-Keyboard-and-Mouse.webp",
        price: 999,
      },
      {
        id: 238,
        name: "Wireless Headset",
        category: "Stools",
        imageUrl: "https://i.ibb.co/1Jcc6x7/Wireless-Headset.webp ",
        price: 999,
      },
      {
        id: 39,
        name: "Epson printer",
        category: "Stools",
        imageUrl: "https://i.ibb.co/Qv4HxF1/Epson-printer.webp ",
        price: 999,
      },
      {
        id: 40,
        name: "Bluetooth Speaker",
        category: "Stools",
        imageUrl: "https://i.ibb.co/xX9TGZh/symfonisk-wifi-bookshelf-speaker-black-smart-gen-2.webp ",
        price: 999,
      },
      {
        id: 41,
        name: "Powerboard 3 way socket with usb ports",
        category: "Stools",
        imageUrl: "https://i.ibb.co/qksspTW/hagsta-3-way-socket-with-2-usb-ports.webp",
        price: 19,
      },
    ],
  },

  Ottomans: {
    id: 5,
    category: "Others",
    routeName: "ottomans",
    items: [
      {
        id: 42,
        name: "Monitor Stand",
        category: "Ottomans",
        imageUrl: " https://i.ibb.co/17VBd16/sigfinn-monitor-stand-fixed-height-white.webp ",
        price: 1,
      },
      {
        id: 43,
        name: "Memo board",
        category: "Ottomans",
        imageUrl: "https://i.ibb.co/8Kkfv0M/svensas-memo-board-with-pins-beige.webp",
        price: 19,
      },
      {
        id: 44,
        name: "Desk Organiser",
        category: "Ottomans",
        imageUrl: "https://i.ibb.co/7zmjm7n/risatorp-desk-organiser-white.webp ",
        price: 19,
      },
      {
        id: 45,
        name: "Wireless Charger",
        category: "Ottomans",
        imageUrl: "https://i.ibb.co/rQ6jyPp/livboj-wireless-charger-white-1.webp",
        price: 19,
      },
      {
        id: 46,
        name: "Janus",
        category: "Ottomans",
        imageUrl: "https://i.ibb.co/MhvNwds/janus.jpg ",
        price: 19,
      },
      {
        id: 47,
        name: "Maricus",
        category: "Ottomans",
        imageUrl: "https://i.ibb.co/LkJj3hM/maricus.jpg ",
        price: 19,
      },
      {
        id: 48,
        name: "Nerio",
        category: "Ottomans",
        imageUrl: " https://i.ibb.co/7JG3LXr/nerio.jpg ",
        price: 19,
      },
      {
        id: 49,
        name: "Hercules",
        category: "Ottomans",
        imageUrl: "  https://i.ibb.co/1zCmJB3/hercules.jpg",
        price: 19,
      },
    ],
  },
};

export default SHOP_DATA;
